export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_RESET = 'CATEGORIES_RESET';

export const FORUMS_LOADING = 'FORUMS_LOADING';
export const FORUMS_LOADED = 'FORUMS_LOADED';
export const FORUMS_RESET = 'FORUMS_RESET';

export const THREADS_LOADING = 'THREADS_LOADING';
export const THREADS_LOADED = 'THREADS_LOADED';
export const THREADS_RESET = 'THREADS_RESET';

export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_RESET = 'POSTS_RESET';
export const ADD_POST = 'POST_ADD';
export const DELETE_POST = 'POST_DELETE';